anthony = User.create(username: "Sarah", password: "test")
User.create(username: "anthony", password: "anthony")
Doll.create(user: anthony, name: 'English Professor', story: "My stupid english professor gave me a B because I turned in an assignment one day late after recovering from the flu. I hope he rots in hell.")
Doll.create(name: 'David', story: "He told me everything I ever wanted to hear. I fell madly, deeply in love. Only problem was he told my best friend the same things.")
Doll.create(user: anthony, name: 'President Obama', story: "No story needed")
Doll.create(name: 'Boss from hell', story: "Finally got a promotion after 2 years of hard work. I got a 2% raise, meanwhile he just bought a new Lexus. Asshole.")
Doll.create(name: 'Sally', story: "She's the only girl I ever loved. I wish she'd come back home.")
Doll.create(user: anthony, name: 'Ex-Boyfriend', story: "My stupid english professor gave me a B because I turned in an assignment one day late after recovering from the flu. I hope he rots in hell.")
Doll.create(name: 'Brad Pitt', story: "He told me everything I ever wanted to hear. I fell madly, deeply in love. Only problem was he told my best friend the same things.")
Doll.create(name: 'George Bush, Sr.', story: "No story needed")
Doll.create(user: anthony, name: 'Sam Blackman', story: "Finally got a promotion after 2 years of hard work. I got a 2% raise, meanwhile he just bought a new Lexus. Asshole.")
Doll.create(name: 'Sally', story: "She's the only girl I ever loved. I wish she'd come back home.")
Doll.create(name: 'English Professor', story: "My stupid english professor gave me a B because I turned in an assignment one day late after recovering from the flu. I hope he rots in hell.")
Doll.create(name: 'David', story: "He told me everything I ever wanted to hear. I fell madly, deeply in love. Only problem was he told my best friend the same things.")
Doll.create(name: 'President Obama', story: "No story needed")
Doll.create(name: 'Boss from hell', story: "Finally got a promotion after 2 years of hard work. I got a 2% raise, meanwhile he just bought a new Lexus. Asshole.")
Doll.create(name: 'Sally', story: "She's the only girl I ever loved. I wish she'd come back home.")
Doll.create(name: 'English Professor', story: "My stupid english professor gave me a B because I turned in an assignment one day late after recovering from the flu. I hope he rots in hell.")
Doll.create(name: 'David', story: "He told me everything I ever wanted to hear. I fell madly, deeply in love. Only problem was he told my best friend the same things.")
Doll.create(name: 'President Obama', story: "No story needed")
Doll.create(name: 'Boss from hell', story: "Finally got a promotion after 2 years of hard work. I got a 2% raise, meanwhile he just bought a new Lexus. Asshole.")
Doll.create(name: 'Sally', story: "She's the only girl I ever loved. I wish she'd come back home.")